import Head from "next/head";
import { Inter } from "@next/font/google";
import Navbar from "../components/Navbar";
import Hero from "../components/Hero";
import HouseCard from "../components/HouseCard";
import Image from "next/image";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="p-4 lg:p-16 md:p-8">
        <Navbar />
        <Hero />
        <div className="flex flex-col md:grid md:grid-cols-2 md:grid-rows-3 md:gap-3 lg:grid-cols-3 lg:grid-rows-2 lg:gap-5 my-10 mys:0">
          <HouseCard src="/img/products/1.png" />
          <HouseCard src="/img/products/2.png" />
          <HouseCard src="/img/products/3.png" />
          <HouseCard src="/img/products/4.png" />
          <HouseCard src="/img/products/5.png" />
          <HouseCard src="/img/products/6.png" />
        </div>
      </main>
    </>
  );
}
